[matrix]
homeserver = ""
username = ""
password = ""
room_id = ""
# session_dir = "session"

[gotify]
url = ""
token = ""
# delete_sent = false
# html = "<h4>{{app}}: {{title}}</h4>\n{{message}}"
# plain = "{{app}}: {{title}}\n{{message}}"
# threshold_low = 3
# threshold_high = 8

# [gotify.low]
# html = ""
# plain = ""

# [gotify.normal]
# html = ""
# plain = ""

# [gotify.high]
# html = ""
# plain = ""
